var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                             o  o  o                                            ",
   "            c                                                                   ",
   "          xxxxx                                                               c ",
   "                                                                                ",
   "                   xx                                                           ",
   "                           xxxxxxxxxxx                                          ",
   "                                                         o o                 xxx",
   "  x                                                  xxxxxxxxx               x  ",
   "  x                       o  o                                      o        x  ",
   "  x                   xxxxxxx            x   x                     xxxxxx  xxx  ",
   "  x                                      x!!!x                               x  ",
   "  x  @                                   x!!!x =              =      o       x  ",
   "  xxxxxxxx        xxx#xxxx        xxxxxxxxxxxxxxxxx#xx              xxxxxxxxxx  ",
   "         x        x      x        x                  x              x           ",
   "         x      xxx      x!!!!!!!!x                  x!!!!!!!!!!!!!!x           ",
   "         x        x      x!!!!!!!!x                  x!!!!!!!!!!!!!!x           ",
   "         x=     oox      xxxxxxxxxx                  xxxxxxxxxxxxxxxx           ",
   "         xxxxxxxxxx                                                             ",
   "                                                                                "],
   ["                 xxx                                                            ",
    "                 x|x                                                            ",
    "                                                                     x          ",
    "                                                                    xxx         ",
    "                       o o                                          xvx         ",
    "            c                                                                 c ",
    "          x   x       xx#xx                                                     ",
    "          x#xxx                              c                               xxx",
    "                              o o o                                             ",
    "                   xx                       xxx                          xxx    ",
    "                           xxxxxxxxxxx                  o  o     x#xx           ",
    " x                  c          x                                                ",
    " x                        =    x                     xxxxxxxxx                  ",
    " x               xxxxxx                                                         ",
    " x @                                                                            ",
    " xxxxxxxxx                                                                      ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                xxxxxxxxxxx                                     ",
    "                                                                                ",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
    ["      xxx        xxx                                                            ",
     "      xvx        xvx                                                            ",
     "                                                                     x          ",
     "                                                                    xxx         ",
     "            c          o o                                          xvx         ",
     "                                             c                                c ",
     "          xxxxx       xx#xx                           xxxxxxx                   ",
     "                                                      x     x                xxx",
     "   oo                         o o o                   x     x                   ",
     "                   xx                       xxx       x|xxx|x            xxx    ",
     "   xx                      xxxxxxxx                     o  o     x#xx           ",
     "          c                    x                                                ",
     "                          =    x                     xxxxxxxxx                  ",
     "         xxxx                                  x                                ",
     "                o                                                      xxx      ",
     "                                          xx                                    ",
     "               xx                                                               ",
     "                                    xx                                          ",
     "                                                            xxx                 ",
     "   @      xx#                             xx                                    ",
     " xxx                                                                            ",
     "                                                                                ",
     "!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!xxxxxx!!!!!!xxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
     ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "                              ",
      "                              ",
      "                       o      ",
      "            o                 ",
      "                              ",
      "                              ",
      "                              ",
      "                             o",
      "      o                       ",
      "                              ",
      " c c  cc  c c  c   c c c  c c ",
      " c c c  c c c  c c c c cc c c ",
      "  c  c  c c c  c c c c c cc   ",
      "  c   cc   c    c c  c c  c c ",
      "                              ",
      "                              ",
      "                            o ",
      "                              ",
      "                   o          ",
      "      o                       ",
      "                              ",
      "               @              ",
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
